=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/customer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://mobileoperator.com/schema/customer"
           targetNamespace="http://mobileoperator.com/schema/customer"
        xmlns:base="http://mobileoperator.com/schema/base-types"
           elementFormDefault="qualified">

    <xs:import namespace="http://mobileoperator.com/schema/base-types" schemaLocation="base-types.xsd"/>

    <xs:element name="customer" type="tns:CustomerType"/>

        <xs:complexType name="CustomerType">
            <xs:sequence>
                <xs:element name="id" type="base:idType"/>
                <xs:element name="fullName" type="base:nameType"/>
                <xs:element name="phoneNumber">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="13"/>
                            <xs:maxLength value="13"/>
                            <xs:pattern value="\+380[0-9]{9}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="email" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="5"/>
                            <xs:maxLength value="50"/>
                            <xs:whiteSpace value="collapse"/>
                            <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="createdAt" type="xs:dateTime"/>
                <xs:element name="tariffId" type="base:idType"/>
                <xs:element name="isActive" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>

</xs:schema>

=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<customer xmlns="http://mobileoperator.com/schema/customer"
          xmlns:base="http://mobileoperator.com/schema/base-types"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://mobileoperator.com/schema/customer customer.xsd">
    <id>1</id>
    <fullName>Іваненко Петро</fullName>
    <phoneNumber>+380971234567</phoneNumber>
    <email>ivanenko.p@example.com</email>
    <createdAt>2023-10-15T10:00:00Z</createdAt>
    <tariffId>1</tariffId>
    <isActive>true</isActive>
</customer>

=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/customer-incorrect.xml
<?xml version="1.0" encoding="UTF-8"?>
<customer xmlns="http://mobileoperator.com/schema/customer"
          xmlns:base="http://mobileoperator.com/schema/base-types"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://mobileoperator.com/schema/customer customer.xsd">

    <id>a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c</id>
    <fullName>Іваненко*Петро</fullName>
    <phoneNumber>0971234567</phoneNumber>
    <email>invalid.email.com</email>
    <createdAt>2023-10-15T10:00:00</createdAt>
    <tariffId>f1e2d3c4-b5a6-9b8c-7d6e-5f4a3b2c1d0e</tariffId>
    <isActive>NotBoolean</isActive>
</customer>
