=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/tariff.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://mobileoperator.com/schema/tariff"
           targetNamespace="http://mobileoperator.com/schema/tariff"
           xmlns:base="http://mobileoperator.com/schema/base-types"
           elementFormDefault="qualified">

    <xs:import namespace="http://mobileoperator.com/schema/base-types" schemaLocation="base-types.xsd"/>

    <xs:element name="tariff" type="tns:TariffType"/>

    <xs:complexType name="TariffType">
        <xs:sequence>
            <xs:element name="id" type="base:idType"/>
            <xs:element name="name" type="base:nameType"/>
            <xs:element name="description" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="5"/>
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
            </xs:element>
            <xs:element name="monthlyFee" type="base:moneyZIncType"/>
            <xs:element name="internetLimit" type="xs:nonNegativeInteger"/>
            <xs:element name="callMinutes" type="xs:nonNegativeInteger"/>
            <xs:element name="smsLimit" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/tariff-incorrect.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariff xmlns:tar="http://mobileoperator.com/schema/tariff"
        xmlns:base="http://mobileoperator.com/schema/base-types"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://mobileoperator.com/schema/tariff tariff.xsd">
    <id>f1e2d3c4-b5a6-9b8c-7d6e-5f4a3b2c1d0e</id>
    <name>С</name>
    <description>T</description>
    <monthlyFee>-10.00</monthlyFee>
    <internetLimit>-100</internetLimit>
    <callMinutes>1000</callMinutes>
    <smsLimit xsi:nil="true"/>
</tariff>

=== AlexMozheha/mobile-operator-system/validation/src/main/resources/xml/tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariff xmlns="http://mobileoperator.com/schema/tariff"
        xmlns:base="http://mobileoperator.com/schema/base-types"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://mobileoperator.com/schema/tariff tariff.xsd">
    <id>1</id>
    <name>Безліміт-Преміум</name>
    <description>Повний безліміт на все: дзвінки та інтернет.</description>
    <monthlyFee>350.50</monthlyFee>
    <internetLimit>0</internetLimit>
    <callMinutes>5000</callMinutes>
    <smsLimit>1000</smsLimit>
</tariff>
